server:
  port: 8080

spring:
  application:
    name: erp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension} # 动态加载配置